version: "3"
services:
  ovpn_proxy_melbourne:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Melbourne.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8080
    ports:
      - 8080:8080
    restart: always

  ovpn_proxy_brisbane:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Brisbane.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8081
    ports:
      - 8081:8081
    restart: always

  ovpn_proxy_adelaide:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Adelaide.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8082
    ports:
      - 8082:8082
    restart: always

  ovpn_proxy_perth:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Perth.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8083
    ports:
      - 8083:8083
    restart: always

  ovpn_proxy_auckland:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Auckland.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8084
    ports:
      - 8084:8084
    restart: always

  ovpn_proxy_manchester:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Auckland.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8085
    ports:
      - 8085:8085
    restart: always

  ovpn_proxy_london:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Auckland.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8086
    ports:
      - 8086:8086
    restart: always

  ovpn_proxy_glasgow:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Auckland.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8087
    ports:
      - 8087:8087
    restart: always

  ovpn_proxy_edinburgh:
    image: arbie:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./openvpn-config:/app/ovpn/config
      - ./openvpn-config/credentials.txt:/app/ovpn/config/credentials.txt
    environment:
      - OPENVPN_FILENAME=Auckland.ovpn
      - LOCAL_NETWORK=10.0.1.7/24
      - ONLINECHECK_DELAY=900
      - LISTEN_PORT=8088
    ports:
      - 8088:8088
    restart: always
